#!/bin/sh

#################
# Start redsocks
#################
rs_start() {
    docker run \
        --name="redsocks" \
        --privileged=true \
        --net=host \
        -v /etc/redsocks-whitelist.txt:/etc/redsocks-whitelist.txt \
        -d \
        ncarlier/redsocks
}

################
# Stop redsocks
################
rs_stop() {
    docker stop redsocks
    docker rm redsocks
    #sudo iptables-save | grep -v REDSOCKS | sudo iptables-restore
}

case "$1" in
    start)
        echo -n "Starting REDSOCKS..."
        rs_stop
        rs_start
        echo "done."
        ;;
    stop)
        echo -n "Stoping REDSOCKS..."
        rs_stop
        echo "done."
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0

